name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "post-image-generator"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
    steps:
      - uses: actions/setup-node@v3.5.1
      - uses: actions/checkout@v3
      - run: |
          npm install -g wrangler 
          npx wrangler publish



  
  